### ISSUE TITLE
Getting Test Client to run on Raspberry Pi

### ISSUE THREAD

**Issue by sumps** [SignalK/testclient#1]
If this could be added to the Readme.md at some point it would hopefully help anyone else wanting to use this useful test tool....

Installing mDNS on Raspberry Pi

Need to install the Avahi Libraries using this procedure....

sudo apt-get update
sudo apt-get install libavahi-compat-libdnssd-dev
sudo npm install mdns

Once installed, you should be able to ping your Raspberry Pi by...

ping raspberrypi.local

and discover other devices on your network using this command...

avahi-browse -a -t

**Comment by tkurki** [comment]
Fixed in f8972f319fd16d9e779e2158a02d823092284f83
